package gui;

import models.Lecturer;
import interfaces.Editor;
import javax.swing.JOptionPane;

public class EditProfilePanel extends javax.swing.JPanel implements Editor {
    
    private Lecturer lecturer;
    private LecturerDashboard parentDashboard;
    
    public EditProfilePanel(Lecturer lecturer) {
        this.lecturer = lecturer;
         this.parentDashboard = null;
        initComponents();
        loadData();
    }
    
    @Override
     public void loadData() {
        txtUserID.setText(lecturer.getUserID());
        txtUserName.setText(lecturer.getUsername());
          txtName.setText(lecturer.getName());
            txtEmail.setText(lecturer.getEmail());
            txtPhone.setText(lecturer.getPhone());
         txtDateOfBirth.setText(lecturer.getDateOfBirth());
         
    }
    
    
    @Override
public void saveChanges() {
    String name  = txtName.getText().trim();
    String email = txtEmail.getText().trim();
    String phone = txtPhone.getText().trim();

   
    String newPassword = "";
    if (txtNewPassword instanceof javax.swing.JPasswordField) {
        newPassword = new String(((javax.swing.JPasswordField) txtNewPassword).getPassword()).trim();
    } else {
        newPassword = txtNewPassword.getText().trim(); 
    }

     if (newPassword.isEmpty()) {
    lecturer.updateProfile(name, email, phone);
} else {
    lecturer.updateProfileWithPassword(name, email, phone, newPassword);
}



    if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
        JOptionPane.showMessageDialog(this, "Invalid email format!",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!phone.matches("^01[0-9]{8,9}$")) {
        JOptionPane.showMessageDialog(this, "Invalid phone! Format: 01XXXXXXXX",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


    if (!newPassword.isEmpty()) {
        if (newPassword.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    String oldRawLine = lecturer.findRawLine();


   if (newPassword.isEmpty()) {
    lecturer.updateProfile(name, email, phone);
    } else {
    lecturer.updateProfileWithPassword(name, email, phone, newPassword);
    }

    if (lecturer.updateInFile(oldRawLine)) {
        JOptionPane.showMessageDialog(this, "Profile updated!",
                "Success", JOptionPane.INFORMATION_MESSAGE);

 
        if (lecturer.updateInFile(oldRawLine)) {
    JOptionPane.showMessageDialog(this, "Profile updated!",
            "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
    JOptionPane.showMessageDialog(this, "Failed to update!",
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    } else {
        JOptionPane.showMessageDialog(this, "Failed to update!",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lbluser = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblfullname = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lbldateofbirth = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        topPanel.setBackground(new java.awt.Color(29, 78, 216));
        topPanel.setPreferredSize(new java.awt.Dimension(700, 100));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Edit My Profile");
        lblTitle.setVerifyInputWhenFocusTarget(false);
        topPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        formPanel.setBackground(new java.awt.Color(245, 247, 250));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 80, 40, 80));
        formPanel.setForeground(new java.awt.Color(153, 0, 153));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbluser.setBackground(new java.awt.Color(153, 0, 153));
        lbluser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbluser.setForeground(new java.awt.Color(0, 0, 0));
        lbluser.setText("User ID:");
        formPanel.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        txtUserID.setEditable(false);
        txtUserID.setBackground(new java.awt.Color(204, 204, 204));
        txtUserID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserID.setPreferredSize(new java.awt.Dimension(300, 35));
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        formPanel.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 330, -1));

        lblusername.setBackground(new java.awt.Color(153, 0, 153));
        lblusername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 0, 0));
        lblusername.setText("Username:");
        formPanel.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txtUserName.setBackground(new java.awt.Color(204, 204, 204));
        txtUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserName.setPreferredSize(new java.awt.Dimension(300, 35));
        formPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 330, -1));

        lblfullname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblfullname.setForeground(new java.awt.Color(0, 0, 0));
        lblfullname.setText("Full Name:");
        formPanel.add(lblfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        txtName.setBackground(new java.awt.Color(236, 240, 241));
        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtName.setPreferredSize(new java.awt.Dimension(300, 35));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        formPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 330, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Email:");
        formPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        txtEmail.setBackground(new java.awt.Color(236, 240, 241));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(300, 35));
        formPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 330, -1));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Phone:");
        formPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        txtPhone.setBackground(new java.awt.Color(236, 240, 241));
        txtPhone.setPreferredSize(new java.awt.Dimension(400, 35));
        formPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 330, -1));

        lbldateofbirth.setBackground(new java.awt.Color(255, 0, 0));
        lbldateofbirth.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldateofbirth.setForeground(new java.awt.Color(0, 0, 0));
        lbldateofbirth.setText("Date of Birth:");
        formPanel.add(lbldateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtDateOfBirth.setEditable(false);
        txtDateOfBirth.setBackground(new java.awt.Color(204, 204, 204));
        txtDateOfBirth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDateOfBirth.setPreferredSize(new java.awt.Dimension(400, 35));
        formPanel.add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 330, -1));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        formPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        txtNewPassword.setBackground(new java.awt.Color(236, 240, 241));
        txtNewPassword.setPreferredSize(new java.awt.Dimension(400, 35));
        formPanel.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 330, -1));

        add(formPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 40));

        btnSave.setBackground(new java.awt.Color(37, 99, 235));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Changes");
        btnSave.setBorderPainted(false);
        btnSave.setFocusPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(239, 68, 68));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveChanges();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            loadData();
             JOptionPane.showMessageDialog(
        this,
        "Changes have been cancelled.",
        "Cancelled",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbldateofbirth;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
