/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.FileManager;
import models.User;
import utils.AuthManager;
import utils.TableStyler;

/**
 *
 * @author Hussain Alkhaldi
 */
public class DeleteUserPanel extends javax.swing.JPanel {
    private User loggedInUser;


    public DeleteUserPanel(User loggedInUser) {
        this.loggedInUser = loggedInUser;
        initComponents();
        loadUsers();
        TableStyler.styleTable(tblUsers);
    }
    
    private void loadUsers() {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();  
        model.setRowCount(0);  
        
        List<String> users = FileManager.readFile(FileManager.USERS_FILE);
        
        for (String line : users) {
            String[] parts = line.split("\\|");
            if (parts.length >= 9) {
  
                model.addRow(new Object[]{
                    parts[0],  // User ID
                    parts[1],  // Username
                    parts[3],  // Name
                    parts[8]   // Type
                });
            }
        }
    }
    
     private void deleteUser() {
        int row = tblUsers.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a user to delete", 
                "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        String userID = (String) model.getValueAt(row, 0);
        String username = (String) model.getValueAt(row, 1);
        
   
        if (userID.equals(loggedInUser.getUserID())) {
            int confirm = JOptionPane.showConfirmDialog(this,
                "You are about to delete your own account!\n" +
                "This will close the application.\n\n" +
                "Are you sure you want to delete yourself?",
                "Delete Own Account", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if (confirm == JOptionPane.YES_OPTION) {
                User user = AuthManager.findUserByID(userID);
                if (user != null && user.deleteFromFile()) {
                    JOptionPane.showMessageDialog(this, 
                        "Your account has been deleted.", 
                        "Account Deleted", JOptionPane.INFORMATION_MESSAGE);
                    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
                }
            }
            return;
        }
        
      
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete user: " + username + " (" + userID + ")?", 
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            User user = AuthManager.findUserByID(userID);
            
            if (user != null && user.deleteFromFile()) {
                JOptionPane.showMessageDialog(this, 
                    "User deleted successfully!", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                loadUsers();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Failed to delete user. Please try again.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 620));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(220, 38, 38));
        headerPanel.setPreferredSize(new java.awt.Dimension(900, 80));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Delete User");
        headerPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 840, 40));

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(243, 244, 246));
        buttonPanel.setPreferredSize(new java.awt.Dimension(900, 40));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(220, 38, 38));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE USER");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 5, 130, 30));

        btnRefresh.setBackground(new java.awt.Color(16, 185, 129));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        buttonPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 5, 100, 30));

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblUsers.setPreferredSize(new java.awt.Dimension(1000, 950));
        tblUsers.setRowHeight(35);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteUser();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadUsers();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
