/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import utils.FileManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import models.User;
import utils.AuthManager;
import utils.TableStyler;
import interfaces.Editor;
/**
 *
 * @author Hussain Alkhaldi
 */
public class UpdateUserPanel extends BaseFormPanel implements Editor {
    
        @Override
    public void loadData() {
        loadUsers();
    }
    
    @Override
    public void saveChanges() {
        editSelectedUser();
    
    }
    
    
        @Override
    protected boolean validateInput() {
       
        return true;
    }

    public UpdateUserPanel() {
        initComponents();
        loadUsers();
        TableStyler.styleTable(tblUsers);
    }
     private void loadUsers() {
    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel(); 
    model.setRowCount(0);

    List<String> users = FileManager.readFile(FileManager.USERS_FILE);

for (String line : users) {
    String[] parts = line.split("\\|");
    if (parts.length >= 9) {
        Object[] row = {
            parts[0],  // ID
            parts[1],  // Username
            parts[3],  // Name
            parts[4],  // Gender
            parts[5],  // Email
            parts[6],  // Phone
            parts[7],  // Date of Birth (DOB)
            parts[8]   // Type
        };
        model.addRow(row);
    }
}
}


    
private void editSelectedUser() {
        int selectedRow = tblUsers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a user to edit",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        String userID = (String) model.getValueAt(selectedRow, 0);

       
        User user = AuthManager.findUserByID(userID);

        if (user != null) {
            Window window = SwingUtilities.getWindowAncestor(this);
            EditUserDialog dialog = new EditUserDialog(window, user.findRawLine());
            dialog.setVisible(true);
            loadUsers();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 620));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(124, 58, 237));
        headerPanel.setPreferredSize(new java.awt.Dimension(900, 80));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Select a User to Update");
        headerPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 840, 40));

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(243, 244, 246));
        buttonPanel.setForeground(new java.awt.Color(255, 255, 255));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setBackground(new java.awt.Color(59, 130, 246));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT SELECTED");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 7, 140, 30));

        btnRefresh.setBackground(new java.awt.Color(16, 185, 129));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        buttonPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 7, 100, 30));

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Name", "Gender", "Email", "Phone", "Date of Birth", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblUsers.setPreferredSize(new java.awt.Dimension(1000, 950));
        tblUsers.setRowHeight(35);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

     class EditUserDialog extends BaseDialog {
    
        private String originalData;
        private String[] userParts;
        private JTextField txtName, txtEmail, txtPhone;
        private JComboBox<String> cmbGender;
        private JButton btnSave, btnCancel;
        private JPanel headerPanel;
        private JLabel lblTitle, lblInfo;
        private JPanel formPanel;
        private JPanel buttonPanel;
        public EditUserDialog(Window parent, String userData) {
            super(parent, "Edit User");  
            this.originalData = userData;
            this.userParts = userData.split("\\|");
            
            initializeComponents();
            setupLayout();
            populateFields();
            setupEnterKeyNavigation();
            setupRealTimeValidation();
        }
        
@Override
        protected void initializeComponents() {
            setSize(600, 520);
            setLocationRelativeTo(getParent());
            setResizable(false);
            
            txtName = new JTextField();
            txtEmail = new JTextField();
            txtPhone = new JTextField();
            
            txtName.setFont(new Font("Arial", Font.PLAIN, 14));
            txtEmail.setFont(new Font("Arial", Font.PLAIN, 14));
            txtPhone.setFont(new Font("Arial", Font.PLAIN, 14));
            
            txtName.setBorder(BorderFactory.createLineBorder(BORDER_DEFAULT_COLOR));
            txtEmail.setBorder(BorderFactory.createLineBorder(BORDER_DEFAULT_COLOR));
            txtPhone.setBorder(BorderFactory.createLineBorder(BORDER_DEFAULT_COLOR));
            

            
            cmbGender = new JComboBox<>(new String[]{"Male", "Female"});
            cmbGender.setFont(new Font("Arial", Font.PLAIN, 14));
            
            btnSave = new JButton("SAVE CHANGES");
            btnSave.setFont(new Font("Arial", Font.BOLD, 13));
            btnSave.setForeground(Color.WHITE);
            btnSave.setBackground(new Color(16, 185, 129));
            btnSave.setPreferredSize(new Dimension(140, 36));
            btnSave.setFocusPainted(false);
            
            btnCancel = new JButton("CANCEL");
            btnCancel.setFont(new Font("Arial", Font.BOLD, 13));
            btnCancel.setForeground(new Color(107, 114, 128));
            btnCancel.setBackground(Color.WHITE);
            btnCancel.setBorder(BorderFactory.createLineBorder(new Color(209, 213, 219)));
            btnCancel.setPreferredSize(new Dimension(120, 36));
            btnCancel.setFocusPainted(false);
            
            headerPanel = new JPanel();
            lblTitle = new JLabel();
            lblInfo = new JLabel();
            formPanel = new JPanel();
            buttonPanel = new JPanel();
        }
        
        private void setupLayout() {
         
            setLayout(new BorderLayout());
            

            headerPanel.setBackground(new Color(124, 58, 237));
            headerPanel.setPreferredSize(new Dimension(600, 70));
            headerPanel.setLayout(new AbsoluteLayout());
            
            lblTitle.setFont(new Font("Arial", Font.BOLD, 20));
            lblTitle.setForeground(Color.WHITE);
            lblTitle.setText("Edit User: " + userParts[1]);
            headerPanel.add(lblTitle, new AbsoluteConstraints(25, 15, 400, 30));
            
            lblInfo.setFont(new Font("Arial", Font.PLAIN, 12));
            lblInfo.setForeground(new Color(200, 200, 255));
            lblInfo.setText("ID: " + userParts[0]);
            headerPanel.add(lblInfo, new AbsoluteConstraints(25, 45, 300, 20));
            
            add(headerPanel, BorderLayout.NORTH);
           
            formPanel.setBackground(Color.WHITE);
            formPanel.setLayout(new AbsoluteLayout());
            
           
            addLabel(formPanel, "Full Name", 30, 20);
            txtName.setPreferredSize(new Dimension(540, 38));
            formPanel.add(txtName, new AbsoluteConstraints(30, 45, 540, 38));
            
           
            addLabel(formPanel, "Gender", 30, 105);
            cmbGender.setPreferredSize(new Dimension(540, 38));
            formPanel.add(cmbGender, new AbsoluteConstraints(30, 130, 540, 38));
            
            
          
            addLabel(formPanel, "Email", 30, 190);
            txtEmail.setPreferredSize(new Dimension(540, 38));
            formPanel.add(txtEmail, new AbsoluteConstraints(30, 215, 540, 38));
            
           
            addLabel(formPanel, "Phone Number", 30, 275);
            txtPhone.setPreferredSize(new Dimension(540, 38));
            formPanel.add(txtPhone, new AbsoluteConstraints(30, 300, 540, 38));
            
            add(formPanel, BorderLayout.CENTER);
            
           
            buttonPanel.setBackground(new Color(243, 244, 246));
            buttonPanel.setPreferredSize(new Dimension(600, 60));
            buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 15, 12));
            buttonPanel.add(btnCancel);
            buttonPanel.add(btnSave);
            
            add(buttonPanel, BorderLayout.SOUTH);
            
          
            btnSave.addActionListener(e -> saveChanges());
            btnCancel.addActionListener(e -> dispose());
        }
        
    
        private void addLabel(JPanel parent, String text, int x, int y) {
            JLabel lbl = new JLabel(text);
            lbl.setFont(new Font("Arial", Font.BOLD, 13));
            lbl.setForeground(new Color(55, 65, 81));
            parent.add(lbl, new AbsoluteConstraints(x, y, 200, 20));
        }
        
        
        private void setupEnterKeyNavigation() {
            Component[] components = {
                txtName, cmbGender, txtEmail, txtPhone, btnSave
                };
            
            for (int i = 0; i < components.length - 1; i++) {
                final int index = i;
                Component current = components[i];
                
                if (current instanceof JTextField) {
                    ((JTextField) current).addActionListener(e -> components[index + 1].requestFocus());
                } else if (current instanceof JComboBox) {
                    current.addKeyListener(new KeyAdapter() {
                        @Override
                        public void keyPressed(KeyEvent e) {
                            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                                components[index + 1].requestFocus();
                            }
                        }
                    });
                } else if (current instanceof JSpinner) {
                    JComponent editor = ((JSpinner) current).getEditor();
                    if (editor instanceof JSpinner.DefaultEditor) {
                        ((JSpinner.DefaultEditor) editor).getTextField().addActionListener(
                            e -> components[index + 1].requestFocus()
                        );
                    }
                }
            }
        }
        
      
        private void setupRealTimeValidation() {
            txtName.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    String name = txtName.getText().trim();
                    if (!name.isEmpty() && !UpdateUserPanel.this.isValidName(name)) {
                        setError(txtName, true);
                    } else {
                        setError(txtName, false);
                    }
                }
            });
            
            txtEmail.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    String email = txtEmail.getText().trim();
                    if (!email.isEmpty() && !UpdateUserPanel.this.isValidEmail(email)) {
                        setFieldError(txtEmail, true);
                    } else {
                        setFieldError(txtEmail, false);
                    }
                }
            });
            
            txtPhone.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    String phone = txtPhone.getText().trim();
                    if (!phone.isEmpty() && !UpdateUserPanel.this.isValidPhone(phone)) {
                        setFieldError(txtPhone, true);
                    } else {
                        setFieldError(txtPhone, false);
                    }
                }
            });
            

        }

        
        private void populateFields() {
            if (userParts.length >= 9) {
                txtName.setText(userParts[3]);
                cmbGender.setSelectedItem(userParts[4]);
                txtEmail.setText(userParts[5]);
                txtPhone.setText(userParts[6]);
            }
        }
        @Override
        protected void submitForm() {
            saveChanges();
        }
        
        private void saveChanges() {
            try {
                if (!validateInput()) return;
                
             
                User user = User.fromFileString(originalData);
                    user.updateProfile(
                    txtName.getText().trim(),
                    (String) cmbGender.getSelectedItem(),
                    txtEmail.getText().trim(),
                    txtPhone.getText().trim()
                    );
                
                if (user.updateInFile(originalData)) {
                    JOptionPane.showMessageDialog(this, "User updated successfully!", 
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    throw new Exception("Failed to update user data");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
@Override
        protected boolean validateInput() {
            String name = txtName.getText().trim();
            String email = txtEmail.getText().trim();
            String phone = txtPhone.getText().trim();
            
            if (name.isEmpty() || email.isEmpty() || phone.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            if (!UpdateUserPanel.this.isValidName(name)) {  
                setError(txtName, true);
                JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            if (!UpdateUserPanel.this.isValidEmail(email)) {  
                setFieldError(txtEmail, true);
                JOptionPane.showMessageDialog(this, "Invalid email format", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            if (!UpdateUserPanel.this.isValidPhone(phone)) {  
                setFieldError(txtPhone, true);
                JOptionPane.showMessageDialog(this, "Phone must be 10-15 digits", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            return true;
        }
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editSelectedUser();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadUsers();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
