/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.FileManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import models.User;
import utils.TableStyler;

/**
 *
 * @author Hussain Alkhaldi
 */
public class ViewUsersPanel extends javax.swing.JPanel {


public ViewUsersPanel() {
    initComponents();
    setupSearchPanel(); 
    TableStyler.styleTable(tblUsers);      
    loadUsers("All");   
}

private void loadUsers(String filter) {
    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();  
    model.setRowCount(0);
    
    List<User> users = User.getAllUsers(); 
    
    for (User user : users) {
        if (filter.equalsIgnoreCase("All") || user.getUserType().equalsIgnoreCase(filter)) {
            Object[] row = {
                user.getUserID(),
                user.getUsername(),
                user.getName(),
                user.getGender(),
                user.getEmail(),
                user.getPhone(),
                user.getDateOfBirth(),
                user.getUserType()
            };
            model.addRow(row);
        }
    }
}

private void setupSearchPanel() {

    txtSearch.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            searchUsers();
        }
    });
    
    btnSearch.addActionListener(e -> {
        txtSearch.setText("");
        loadUsers((String) cmbFilterType.getSelectedItem());
    });
}


    

    
private void searchUsers() {
    String searchText = txtSearch.getText().trim().toLowerCase();
    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    model.setRowCount(0);
    
    List<String> users = FileManager.readFile(FileManager.USERS_FILE);
    String filter = (String) cmbFilterType.getSelectedItem();
    
    for (String line : users) {
        String[] parts = line.split("\\|");
        if (parts.length >= 9) {
            String userID = parts[0];
            String username = parts[1];
            String name = parts[3];
            String gender = parts[4];
            String email = parts[5];
            String phone = parts[6];
            String type = parts[8];
            
           
            if (!filter.equalsIgnoreCase("All") && !type.equalsIgnoreCase(filter)) {
                continue;
            }
            
          
            if (searchText.isEmpty() ||
                userID.toLowerCase().contains(searchText) ||
                username.toLowerCase().contains(searchText) ||
                name.toLowerCase().contains(searchText) ||
                email.toLowerCase().contains(searchText) ||
                type.toLowerCase().contains(searchText)) {
                
                model.addRow(new Object[]{userID, username, name, gender, email, phone, parts[7], type});
            }
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        filterPanel = new javax.swing.JPanel();
        lblFilter = new javax.swing.JLabel();
        cmbFilterType = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(124, 58, 237));
        headerPanel.setPreferredSize(new java.awt.Dimension(950, 80));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("View All Users");
        headerPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, -1));

        add(headerPanel, java.awt.BorderLayout.NORTH);

        filterPanel.setBackground(new java.awt.Color(243, 244, 246));
        filterPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        filterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFilter.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblFilter.setForeground(new java.awt.Color(55, 65, 81));
        lblFilter.setText("Filter by Type:");
        filterPanel.add(lblFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, -1, -1));

        cmbFilterType.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbFilterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "Academic Leader", "Lecturer", "Student" }));
        cmbFilterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterTypeActionPerformed(evt);
            }
        });
        filterPanel.add(cmbFilterType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(16, 185, 129));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setLabel("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        filterPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Name", "Gender", "Email", "Phone", "Date of Birth", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblUsers.setPreferredSize(new java.awt.Dimension(1000, 950));
        tblUsers.setRowHeight(35);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsers);

        filterPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 920, 380));

        lblSearch.setBackground(new java.awt.Color(55, 65, 81));
        lblSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(55, 65, 81));
        lblSearch.setText("Search:");
        filterPanel.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 5, 80, 30));

        btnSearch.setBackground(new java.awt.Color(59, 130, 246));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("CLEAR");
        filterPanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 5, 100, 30));

        txtSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        filterPanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 7, 160, -1));

        add(filterPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadUsers((String) cmbFilterType.getSelectedItem());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cmbFilterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterTypeActionPerformed
        // TODO add your handling code here:
        loadUsers((String) cmbFilterType.getSelectedItem());
    }//GEN-LAST:event_cmbFilterTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbFilterType;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
