/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import utils.AuthManager;
import models.User;
import javax.swing.*;
import java.awt.*;
import models.ClassGroup;
import models.GradingSystem;

/**
 *
 * @author Hussain Alkhaldi
 */
public class LoginForm extends JFrame {
    
    char defaultEcho;
    
    public LoginForm() {
        User.loadAllUsers();
        GradingSystem.loadAllGrades();    
        ClassGroup.loadAllClasses(); 
          initComponents(); 
          this.setLocationRelativeTo(null);
          addEventListeners();
          loadLogo();
          defaultEcho = txtPassword.getEchoChar();
    }
    private void loadLogo() {
    ImageIcon icon = new ImageIcon(
        getClass().getResource("/images/APU LOGO.png")
    );

    Image img = icon.getImage().getScaledInstance(
        lblLogo.getWidth(),
        lblLogo.getHeight(),
        Image.SCALE_SMOOTH
    );

    lblLogo.setIcon(new ImageIcon(img));
    lblLogo.setText(""); // remove "AFS"
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblSystemName = new javax.swing.JLabel();
        lblSystemName2 = new javax.swing.JLabel();
        lblUniversity = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnHide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assessment Feedback System - Login");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(236, 240, 241));
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setBackground(new java.awt.Color(22, 160, 133));
        logoPanel.setPreferredSize(new java.awt.Dimension(450, 660));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Arial", 1, 72)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("AFS");
        logoPanel.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 200));

        lblSystemName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSystemName.setForeground(new java.awt.Color(255, 255, 255));
        lblSystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemName.setText("Assessment Feedback");
        logoPanel.add(lblSystemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 300, 40));

        lblSystemName2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSystemName2.setForeground(new java.awt.Color(255, 255, 255));
        lblSystemName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemName2.setText("System");
        lblSystemName2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoPanel.add(lblSystemName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 300, 40));

        lblUniversity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUniversity.setForeground(new java.awt.Color(127, 255, 212));
        lblUniversity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniversity.setText("Asia Pacific University");
        lblUniversity.setToolTipText("");
        logoPanel.add(lblUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 300, 30));

        lblVersion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(72, 201, 176));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("v1.0 | 2026");
        logoPanel.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 300, 20));

        mainPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        formPanel.setForeground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(600, 700));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(44, 62, 80));
        lblTitle.setText("Welcome Back!");
        formPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 400, 50));

        lblSubtitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(127, 140, 144));
        lblSubtitle.setText("Sign in to continue to your dashboard");
        formPanel.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, 400, 25));

        lblUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(44, 62, 80));
        lblUsername.setText("Username");
        formPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 400, 25));

        txtUsername.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199), 2));
        formPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 400, 45));

        lblPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(44, 62, 80));
        lblPassword.setText("Password");
        formPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, 400, 25));

        btnLogin.setBackground(new java.awt.Color(22, 160, 133));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        formPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 405, 400, 50));

        lblMessage.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(231, 76, 60));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPanel.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 400, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(149, 165, 166));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot your password? Contact administrator");
        formPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 515, 400, 25));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199), 2));
        formPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, 400, 45));

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N
        btnHide.setBorder(null);
        btnHide.setBorderPainted(false);
        btnHide.setContentAreaFilled(false);
        btnHide.setFocusPainted(false);
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        formPanel.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 325, 45, 45));

        mainPanel.add(formPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 500, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        performLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed

        if (txtPassword.getEchoChar() == (char) 0) {
            // Hide password
            txtPassword.setEchoChar(defaultEcho);
            btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
        } else {
            // Show password
            txtPassword.setEchoChar((char) 0);
            btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
        }
    }//GEN-LAST:event_btnHideActionPerformed

    /**
     * @param args the command line arguments
     */

       private void addEventListeners() {
          
          btnLogin.addActionListener(e -> performLogin());
       
          txtUsername.addActionListener(e -> txtPassword.requestFocusInWindow());

           
          txtPassword.addActionListener(e -> performLogin());
    }

    private void performLogin() {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        
        // Validate input
        if (username.isEmpty() || password.isEmpty()) {
            showMessage("Please enter both username and password", Color.RED);
            return;
        }
        
       
        User user = AuthManager.login(username, password);
        
        if (user != null) {
            showMessage("Login successful! Welcome " + user.getName(), new Color(0, 128, 0));
            
            
            Timer timer = new Timer(1000, e -> {
                dispose();
            
                user.showMenu();
            });
            timer.setRepeats(false);
            timer.start();
            
        } else {
            showMessage("Invalid username or password", Color.RED);
            txtPassword.setText("");
        }
    }
    
    private void showMessage(String message, Color color) {
        lblMessage.setText(message);
        lblMessage.setForeground(color);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblSystemName;
    private javax.swing.JLabel lblSystemName2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniversity;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
