package forms;



import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Student;
import ui.student.panels.StudentEditProfilePanel;
import ui.student.panels.StudentRegisterClassPanel;
import ui.student.panels.StudentViewResultsPanel;
import ui.student.panels.StudentCommentPanel;


/**
 *
 * @author Abdu
 */
public class StudentMenu extends javax.swing.JFrame {
    
    
    private Student student;
    private java.awt.CardLayout cardLayout;
    
    private StudentEditProfilePanel studentEditProfilePanel;
    private StudentCommentPanel studentCommentPanel;
    private StudentRegisterClassPanel studentRegisterClassPanel;
    private StudentViewResultsPanel studentViewResultsPanel;
    public StudentMenu(Student student) {
    initComponents();
    this.student = student;

    cardLayout = (java.awt.CardLayout) contentPanel.getLayout();

    studentEditProfilePanel = new StudentEditProfilePanel();
    contentPanel.add(studentEditProfilePanel, "EDIT");

    studentRegisterClassPanel = new StudentRegisterClassPanel();
    contentPanel.add(studentRegisterClassPanel, "REGISTER");

    studentViewResultsPanel = new StudentViewResultsPanel();
    contentPanel.add(studentViewResultsPanel, "RESULTS");

    studentCommentPanel = new StudentCommentPanel();
    contentPanel.add(studentCommentPanel, "COMMENTS");

    // use real ID from object
    studentEditProfilePanel.refreshProfile(student.getUserID());
    cardLayout.show(contentPanel, "EDIT");

    lblWelcome.setText("Welcome Back " + student.getName() + "!");
}
    
    
    private void logout() {
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            student.logout();
            dispose();
            SwingUtilities.invokeLater(() -> {
                LoginForm loginForm = new LoginForm();
                loginForm.setVisible(true);
            });
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        btnComment = new javax.swing.JButton();
        btnViewResults = new javax.swing.JButton();
        btnRegisterClass = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(0, 102, 0));
        topPanel.setAlignmentX(0.0F);
        topPanel.setAlignmentY(0.0F);
        topPanel.setPreferredSize(new java.awt.Dimension(1200, 80));
        topPanel.setLayout(new java.awt.BorderLayout());

        lblWelcome.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("  Welcome Back Student!");
        topPanel.add(lblWelcome, java.awt.BorderLayout.CENTER);

        btnLogout.setBackground(new java.awt.Color(231, 76, 60));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        topPanel.add(btnLogout, java.awt.BorderLayout.EAST);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        sidebarPanel.setBackground(new java.awt.Color(51, 153, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 620));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComment.setBackground(new java.awt.Color(51, 153, 0));
        btnComment.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnComment.setForeground(new java.awt.Color(255, 255, 255));
        btnComment.setText("Send Comments");
        btnComment.setHideActionText(true);
        btnComment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 60));

        btnViewResults.setBackground(new java.awt.Color(51, 153, 0));
        btnViewResults.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnViewResults.setForeground(new java.awt.Color(255, 255, 255));
        btnViewResults.setText("View Results");
        btnViewResults.setHideActionText(true);
        btnViewResults.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResultsActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnViewResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 60));

        btnRegisterClass.setBackground(new java.awt.Color(51, 153, 0));
        btnRegisterClass.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnRegisterClass.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterClass.setText("Register Classes");
        btnRegisterClass.setHideActionText(true);
        btnRegisterClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterClassActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnRegisterClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 60));

        btnEditProfile.setBackground(new java.awt.Color(51, 153, 0));
        btnEditProfile.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnEditProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProfile.setText("Edit Profile");
        btnEditProfile.setHideActionText(true);
        btnEditProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });
        sidebarPanel.add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 60));

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        contentPanel.setBackground(new java.awt.Color(0, 51, 0));
        contentPanel.setPreferredSize(new java.awt.Dimension(950, 620));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        studentCommentPanel.refreshComments(student.getUserID());
        cardLayout.show(contentPanel, "COMMENTS");
    }//GEN-LAST:event_btnCommentActionPerformed

    private void btnViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResultsActionPerformed
        studentViewResultsPanel.refreshResults(student.getUserID());  // use the field you already have
        cardLayout.show(contentPanel, "RESULTS");

    }//GEN-LAST:event_btnViewResultsActionPerformed

    private void btnRegisterClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClassActionPerformed
        studentRegisterClassPanel.refreshRegister(student.getUserID());
        cardLayout.show(contentPanel, "REGISTER");
    }//GEN-LAST:event_btnRegisterClassActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
    studentEditProfilePanel.refreshProfile(this.student.getUserID());
    cardLayout.show(contentPanel, "EDIT");
    }//GEN-LAST:event_btnEditProfileActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new StudentShellFrame("U001").setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisterClass;
    private javax.swing.JButton btnViewResults;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
