package afs.users;

import models.User;
import models.AcademicLeader;
import models.Module;
import models.LecturerAssignment;
import utils.ModuleManager;
import utils.AssignmentManager;
import utils.ClassManager;  
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.*;
import java.awt.*;
import java.util.List;
import utils.ModuleLecturerAssignmentManager;

public class ManageModulesPanel extends javax.swing.JPanel {

    private final AcademicLeader leader;
    private final AcademicLeaderMenu menu;
    private DefaultTableModel tableModel;
    
    public ManageModulesPanel(AcademicLeader leader, AcademicLeaderMenu menu) {
        this.leader = leader;
        this.menu = menu;
        initComponents();
        
        
        setupTable();
        loadModules();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnAssignLecturer = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        moduleTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        tittlePanel.setBackground(new java.awt.Color(255, 170, 85));
        tittlePanel.setPreferredSize(new java.awt.Dimension(867, 60));
        tittlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Module Managment");
        tittlePanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        add(tittlePanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(255, 245, 200));
        buttonPanel.setPreferredSize(new java.awt.Dimension(867, 60));

        btnAssignLecturer.setBackground(new java.awt.Color(255, 245, 200));
        btnAssignLecturer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAssignLecturer.setForeground(new java.awt.Color(0, 0, 0));
        btnAssignLecturer.setText("Assign Lecturer");
        btnAssignLecturer.setPreferredSize(new java.awt.Dimension(150, 35));
        btnAssignLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignLecturerActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAssignLecturer);

        btnAdd.setBackground(new java.awt.Color(255, 245, 200));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText(" Add Module");
        btnAdd.setPreferredSize(new java.awt.Dimension(150, 35));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAdd);

        btnEdit.setBackground(new java.awt.Color(255, 245, 200));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit module");
        btnEdit.setPreferredSize(new java.awt.Dimension(150, 35));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEdit);

        btnDelete.setBackground(new java.awt.Color(255, 245, 200));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete Module");
        btnDelete.setPreferredSize(new java.awt.Dimension(160, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDelete);

        btnClear.setBackground(new java.awt.Color(255, 245, 200));
        btnClear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(160, 35));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        buttonPanel.add(btnClear);

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        moduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ModuleID", "Code", "Name", "Assigned lecturer", "Credits", "Semester", "Description"
            }
        ));
        moduleTable.setRowHeight(25);
        moduleTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(moduleTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignLecturerActionPerformed
       assignLecturer();
    }//GEN-LAST:event_btnAssignLecturerActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addModule();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       deleteModule();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editModule();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        moduleTable.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAssignLecturer;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable moduleTable;
    private javax.swing.JPanel tittlePanel;
    // End of variables declaration//GEN-END:variables



    private void setupTable() {
        String[] columns = {
            "ModuleID",
            "Code",
            "Name",
            "Assigned lecturer",
            "Credits",
            "Semester",
            "Description"
        };
            
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
            
     
        moduleTable.setModel(tableModel);
        moduleTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
       
        moduleTable.getColumnModel().getColumn(0).setPreferredWidth(80);   
        moduleTable.getColumnModel().getColumn(1).setPreferredWidth(80);   
        moduleTable.getColumnModel().getColumn(2).setPreferredWidth(200); 
        moduleTable.getColumnModel().getColumn(3).setPreferredWidth(160);  
        moduleTable.getColumnModel().getColumn(4).setPreferredWidth(60);  
        moduleTable.getColumnModel().getColumn(5).setPreferredWidth(100); 
        moduleTable.getColumnModel().getColumn(6).setPreferredWidth(250);  
    }
    
 
    private void loadModules() {
    tableModel.setRowCount(0); 

    List<Module> modules = ModuleManager.getAllModules();

    for (Module module : modules) {
        Object[] row = {
            module.getModuleID(),
            module.getModuleCode(),
            module.getModuleName(),
            AssignmentManager.getLecturerNamesForModule(module.getModuleID()),
            module.getCredits(),
            module.getSemester(),
            module.getDescription()
        };
        tableModel.addRow(row);
    }
}

    

    private void applyLettersOnlyFilter(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) 
                    throws BadLocationException {
                if (string != null && string.matches("[a-zA-Z ]*")) {
                    super.insertString(fb, offset, string, attr);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) 
                    throws BadLocationException {
                if (text != null && text.matches("[a-zA-Z ]*")) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    

    private void applyCodeFilter(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) 
                    throws BadLocationException {
                if (string != null && string.matches("[A-Z0-9-]*")) {
                    super.insertString(fb, offset, string.toUpperCase(), attr);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) 
                    throws BadLocationException {
                if (text != null && text.matches("[A-Z0-9-]*")) {
                    super.replace(fb, offset, length, text.toUpperCase(), attrs);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    

    private void applyNumbersOnlyFilter(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) 
                    throws BadLocationException {
                if (string != null && string.matches("[0-9]*")) {
                    super.insertString(fb, offset, string, attr);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) 
                    throws BadLocationException {
                if (text != null && text.matches("[0-9]*")) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    

    private void applyNumbersAndSpacesFilter(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) 
                    throws BadLocationException {
                if (string != null && string.matches("[0-9 ]*")) {
                    super.insertString(fb, offset, string, attr);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) 
                    throws BadLocationException {
                if (text != null && text.matches("[0-9 ]*")) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    
  
    private void addModule() {
        JTextField txtModuleName = new JTextField(20);
        JTextField txtModuleCode = new JTextField(10);
        JTextField txtCredits = new JTextField(5);
        JTextField txtSemester = new JTextField(15);
        JTextField txtDescription = new JTextField(30);
        
      
        applyLettersOnlyFilter(txtModuleName);
        applyCodeFilter(txtModuleCode);
        applyNumbersOnlyFilter(txtCredits);
        applyNumbersAndSpacesFilter(txtSemester);
        
        JPanel panel = new JPanel(new GridLayout(5, 2, 10, 10));
        panel.add(new JLabel("Module Name:"));
        panel.add(txtModuleName);
        panel.add(new JLabel("Module Code:"));
        panel.add(txtModuleCode);
        panel.add(new JLabel("Credits:"));
        panel.add(txtCredits);
        panel.add(new JLabel("Semester:"));
        panel.add(txtSemester);
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        
        
        while (true) {
            int result = JOptionPane.showConfirmDialog(
                this, 
                panel, 
                "Add New Module", 
                JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.PLAIN_MESSAGE
            );
            
            if (result != JOptionPane.OK_OPTION) {
                return; 
            }
            
            String name = txtModuleName.getText().trim();
            String code = txtModuleCode.getText().trim().toUpperCase();
            String creditsStr = txtCredits.getText().trim();
            String semester = txtSemester.getText().trim();
            String description = txtDescription.getText().trim();
            
           
            if (name.isEmpty() || code.isEmpty() || creditsStr.isEmpty() || semester.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Please fill in all required fields!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!name.matches("[a-zA-Z ]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module Name can only contain letters and spaces!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!code.matches("[A-Z0-9-]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module Code can only contain letters, numbers, and hyphens!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!semester.matches("[0-9 ]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Semester can only contain numbers and spaces!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            int credits;
            try {
                credits = Integer.parseInt(creditsStr);
                if (credits <= 0) {
                    JOptionPane.showMessageDialog(
                        this, 
                        "Credits must be a positive number!", 
                        "Validation Error", 
                        JOptionPane.ERROR_MESSAGE
                    );
                    continue; 
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Credits must be a valid number!", 
                    "Input Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            
            String moduleID = ModuleManager.generateNextModuleID();
            Module newModule = new Module(moduleID, name, code, credits, description, semester);
            
            if (ModuleManager.addModule(newModule)) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module added successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                loadModules();
                return; 
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Failed to add module. Code may already exist.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
        }
    }

    private void editModule() {
        int selectedRow = moduleTable.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this, 
                "Please select a module to edit!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        String moduleID = (String) tableModel.getValueAt(selectedRow, 0);
        Module module = ModuleManager.findModuleByID(moduleID);
        
        if (module == null) {
            JOptionPane.showMessageDialog(
                this, 
                "Module not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        JTextField txtModuleName = new JTextField(module.getModuleName(), 20);
        JTextField txtModuleCode = new JTextField(module.getModuleCode(), 10);
        JTextField txtCredits = new JTextField(String.valueOf(module.getCredits()), 5);
        JTextField txtSemester = new JTextField(module.getSemester(), 15);
        JTextField txtDescription = new JTextField(module.getDescription(), 30);
        
        
        applyLettersOnlyFilter(txtModuleName);
        applyCodeFilter(txtModuleCode);
        applyNumbersOnlyFilter(txtCredits);
        applyNumbersAndSpacesFilter(txtSemester);
        
        JPanel panel = new JPanel(new GridLayout(5, 2, 10, 10));
        panel.add(new JLabel("Module Name:"));
        panel.add(txtModuleName);
        panel.add(new JLabel("Module Code:"));
        panel.add(txtModuleCode);
        panel.add(new JLabel("Credits:"));
        panel.add(txtCredits);
        panel.add(new JLabel("Semester:"));
        panel.add(txtSemester);
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        
       
        while (true) {
            int result = JOptionPane.showConfirmDialog(
                this, 
                panel, 
                "Edit Module", 
                JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.PLAIN_MESSAGE
            );
            
            if (result != JOptionPane.OK_OPTION) {
                return; 
            }
            
            String name = txtModuleName.getText().trim();
            String code = txtModuleCode.getText().trim().toUpperCase();
            String creditsStr = txtCredits.getText().trim();
            String semester = txtSemester.getText().trim();
            String description = txtDescription.getText().trim();
            
            
            if (name.isEmpty() || code.isEmpty() || creditsStr.isEmpty() || semester.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Please fill in all required fields!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!name.matches("[a-zA-Z ]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module Name can only contain letters and spaces!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!code.matches("[A-Z0-9-]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module Code can only contain letters, numbers, and hyphens!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            if (!semester.matches("[0-9 ]+")) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Semester can only contain numbers and spaces!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            int credits;
            try {
                credits = Integer.parseInt(creditsStr);
                if (credits <= 0) {
                    JOptionPane.showMessageDialog(
                        this, 
                        "Credits must be a positive number!", 
                        "Validation Error", 
                        JOptionPane.ERROR_MESSAGE
                    );
                    continue;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Credits must be a valid number!", 
                    "Input Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
            
            
            Module updatedModule = new Module(moduleID, name, code, credits, description, semester);
           
            if (module.getAssignedLecturer() != null && !module.getAssignedLecturer().isEmpty()) {
                updatedModule.setAssignedLecturer(module.getAssignedLecturer());
            }
            
            if (ModuleManager.updateModule(module, updatedModule)) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module updated successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                loadModules();
                return; 
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Failed to update module!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
                continue; 
            }
        }
    }
    
 
    private void deleteModule() {
        int selectedRow = moduleTable.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this, 
                "Please select a module to delete!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        String moduleID = (String) tableModel.getValueAt(selectedRow, 0);
        String moduleName = (String) tableModel.getValueAt(selectedRow, 2);
        
        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to delete module:\n" + moduleName + "?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            Module module = ModuleManager.findModuleByID(moduleID);
            
            if (module != null && ModuleManager.deleteModule(module)) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Module deleted successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                loadModules();
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Failed to delete module!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }
    

    private void assignLecturer() {
        int selectedRow = moduleTable.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module first!", 
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String moduleID = (String) tableModel.getValueAt(selectedRow, 0);
        String moduleCode = (String) tableModel.getValueAt(selectedRow, 1);
        String moduleName = (String) tableModel.getValueAt(selectedRow, 2);
        
        List<User> lecturers = AssignmentManager.getAllLecturers();
        
        if (lecturers.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No lecturers found in the system!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JComboBox<String> lecturerCombo = new JComboBox<>();
        for (User lecturer : lecturers) {
            lecturerCombo.addItem(lecturer.getUserID() + " - " + lecturer.getName());
        }
        
        JTextField txtSemester = new JTextField("Semester 1", 15);
        JTextField txtYear = new JTextField("2025", 10);
        JTextField txtSchedule = new JTextField("TBA", 20);
        
        JPanel panel = new JPanel(new GridLayout(5, 2, 10, 10));
        panel.add(new JLabel("Module:"));
        panel.add(new JLabel(moduleCode + " - " + moduleName));
        panel.add(new JLabel("Select Lecturer:"));
        panel.add(lecturerCombo);
        panel.add(new JLabel("Semester:"));
        panel.add(txtSemester);
        panel.add(new JLabel("Year:"));
        panel.add(txtYear);
        panel.add(new JLabel("Schedule:"));
        panel.add(txtSchedule);
        
        int result = JOptionPane.showConfirmDialog(this, panel, 
            "Assign Lecturer to Module", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            String lecturerSelection = (String) lecturerCombo.getSelectedItem();
            
            if (lecturerSelection == null) {
                JOptionPane.showMessageDialog(this, "Please select a lecturer!", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String lecturerID = parseLecturerId(lecturerSelection);
            String lecturerName = lecturerSelection.substring(lecturerSelection.indexOf(" - ") + 3);
            String semester = txtSemester.getText().trim();
            String year = txtYear.getText().trim();
            String schedule = txtSchedule.getText().trim();

            if (lecturerID.isEmpty() || semester.isEmpty() || year.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Please fill in all required fields (Lecturer, Semester, Year).",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!year.matches("\\d{4}")) {
                JOptionPane.showMessageDialog(this, 
                    "Year must be a 4-digit number (e.g., 2025).",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

           


            
            Module module = ModuleManager.findModuleByID(moduleID);
            if (module != null) {
                module.setAssignedLecturer(lecturerName);
                ModuleManager.updateModule(module, module);
            }


AssignmentManager.deleteAssignmentsByModule(moduleID);

String assignmentID = AssignmentManager.generateNextAssignmentID();

LecturerAssignment assignment = new LecturerAssignment(
    assignmentID, lecturerID, moduleID, semester, year
);

if (AssignmentManager.addAssignment(assignment)) {

    JOptionPane.showMessageDialog(this, 
        "Lecturer assigned successfully!\n" +
        "Class created for module: " + moduleCode + "\n" +
        "Students can now enroll.", 
        "Success", JOptionPane.INFORMATION_MESSAGE);
    loadModules();
} else {
    JOptionPane.showMessageDialog(this, "Failed to save assignment record!", 
        "Warning", JOptionPane.WARNING_MESSAGE);
}

    }
    }

    private String parseLecturerId(String selection) {
        if (selection == null) return "";
        int idx = selection.indexOf(" - ");
        return (idx > 0) ? selection.substring(0, idx).trim() : selection.trim();
    }
}