package afs.users;

import models.ReportGenerator;
import utils.ModuleManager;
import utils.ClassManager;
import utils.AssignmentManager;
import models.LecturerAssignment;
import models.AcademicLeader;
import afs.users.AcademicLeaderMenu;
import models.User;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import java.util.ArrayList;
import utils.ModuleLecturerAssignmentManager;


public class ReportsPanel extends javax.swing.JPanel {
    
    private AcademicLeader leader;
    private AcademicLeaderMenu menu;
    private DefaultTableModel tableModel;
    
    public ReportsPanel(AcademicLeader leader, AcademicLeaderMenu menu) {
        this.leader = leader;
        this.menu = menu;
        initComponents();
        setupTable();
        loadLecturers();
        loadReportData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        buttonPanel = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        statsDisplayPanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        lblFilter = new javax.swing.JLabel();
        lecturerCombo = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        statsHeaderPanel = new javax.swing.JPanel();
        lblStatsTitle = new javax.swing.JLabel();

        tittlePanel.setBackground(new java.awt.Color(255, 170, 85));
        tittlePanel.setPreferredSize(new java.awt.Dimension(859, 60));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Reports & Statistics");
        tittlePanel.add(lblTitle);

        jSeparator4.setForeground(new java.awt.Color(255, 245, 200));

        jSeparator8.setForeground(new java.awt.Color(255, 245, 200));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        buttonPanel.setBackground(new java.awt.Color(255, 245, 200));
        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        buttonPanel.setMaximumSize(new java.awt.Dimension(718, 67));
        buttonPanel.setPreferredSize(new java.awt.Dimension(718, 75));
        buttonPanel.setVerifyInputWhenFocusTarget(false);
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnExport.setBackground(new java.awt.Color(255, 245, 200));
        btnExport.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExport.setForeground(new java.awt.Color(0, 0, 0));
        btnExport.setText("Export Report");
        btnExport.setPreferredSize(new java.awt.Dimension(146, 50));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExport);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);

        statsDisplayPanel.setBackground(new java.awt.Color(255, 245, 200));
        statsDisplayPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        statsDisplayPanel.setForeground(new java.awt.Color(0, 0, 0));
        statsDisplayPanel.setLayout(new java.awt.BorderLayout(10, 10));

        filterPanel.setBackground(new java.awt.Color(255, 245, 200));
        filterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        filterPanel.setPreferredSize(new java.awt.Dimension(100, 60));
        filterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        lblFilter.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblFilter.setForeground(new java.awt.Color(0, 0, 0));
        lblFilter.setText("Filter by lecturer");
        filterPanel.add(lblFilter);

        lecturerCombo.setBackground(new java.awt.Color(255, 245, 200));
        lecturerCombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lecturerCombo.setPreferredSize(new java.awt.Dimension(250, 30));
        lecturerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerComboActionPerformed(evt);
            }
        });
        filterPanel.add(lecturerCombo);

        btnRefresh.setBackground(new java.awt.Color(255, 245, 200));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorderPainted(false);
        btnRefresh.setFocusPainted(false);
        btnRefresh.setPreferredSize(new java.awt.Dimension(120, 30));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        filterPanel.add(btnRefresh);

        statsDisplayPanel.add(filterPanel, java.awt.BorderLayout.PAGE_START);

        scrollPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        reportTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Lecturer ID", "Lecturer Name", "Module Code", "Module Name ", "Semester", "Year"
            }
        ));
        reportTable.setGridColor(new java.awt.Color(255, 245, 200));
        reportTable.setRowHeight(30);
        reportTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane.setViewportView(reportTable);
        if (reportTable.getColumnModel().getColumnCount() > 0) {
            reportTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            reportTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            reportTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            reportTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            reportTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            reportTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        statsDisplayPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        add(statsDisplayPanel, java.awt.BorderLayout.CENTER);

        statsHeaderPanel.setBackground(new java.awt.Color(255, 170, 85));
        statsHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        statsHeaderPanel.setForeground(new java.awt.Color(0, 0, 0));
        statsHeaderPanel.setPreferredSize(new java.awt.Dimension(593, 60));

        lblStatsTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblStatsTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblStatsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblStatsTitle.setText("Reports & Statistics");
        statsHeaderPanel.add(lblStatsTitle);

        add(statsHeaderPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void lecturerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerComboActionPerformed
        loadReportData();
    }//GEN-LAST:event_lecturerComboActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportReport();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadLecturers();
        loadReportData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblStatsTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox<String> lecturerCombo;
    private javax.swing.JTable reportTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel statsDisplayPanel;
    private javax.swing.JPanel statsHeaderPanel;
    private javax.swing.JPanel tittlePanel;
    // End of variables declaration//GEN-END:variables


    private void setupTable() {
        String[] columns = {
            "Lecturer ID",
            "Lecturer Name",
            "Module Code",
            "Module Name",
            "Semester",
            "Year"
        };
        
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        reportTable.setModel(tableModel);
        reportTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        reportTable.setFont(new Font("Arial", Font.PLAIN, 12));
        reportTable.setRowHeight(30);
        
      
        reportTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        reportTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        reportTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        reportTable.getColumnModel().getColumn(3).setPreferredWidth(200);
        reportTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        reportTable.getColumnModel().getColumn(5).setPreferredWidth(80);
    }
    
 
    private void loadLecturers() {
        lecturerCombo.removeAllItems();
        
        
        lecturerCombo.addItem("All Lecturers");
        
       
        List<User> allLecturers = AssignmentManager.getAllLecturers();
        List<User> filteredLecturers = new ArrayList<>();
        
       
        for (User lecturer : allLecturers) {
            if (lecturer.getUserID().startsWith("T")) {
                filteredLecturers.add(lecturer);
            }
        }
        
        
        for (User lecturer : filteredLecturers) {
            lecturerCombo.addItem(lecturer.getUserID() + " - " + lecturer.getName());
        }
    }
    

    private void loadReportData() {
        tableModel.setRowCount(0); 
        
        String selectedItem = (String) lecturerCombo.getSelectedItem();
        if (selectedItem == null) return;
        
   
        List<LecturerAssignment> assignments = ModuleLecturerAssignmentManager.getAllAssignments();
        
        for (LecturerAssignment assignment : assignments) {
            
            if (!assignment.getLecturerID().startsWith("T")) {
                continue; 
            }
            
         
            if (!selectedItem.equals("All Lecturers")) {
                String selectedLecturerID = selectedItem.split(" - ")[0];
                if (!assignment.getLecturerID().equals(selectedLecturerID)) {
                    continue; 
                }
            }
            
          
            User lecturer = findUserByID(assignment.getLecturerID());
            String lecturerName = lecturer != null ? lecturer.getName() : "Unknown";
            
           
            var module = ModuleManager.findModuleByID(assignment.getModuleID());
            String moduleCode = module != null ? module.getModuleCode() : "N/A";
            String moduleName = module != null ? module.getModuleName() : "Unknown";
            

            Object[] row = {
                assignment.getLecturerID(),
                lecturerName,
                moduleCode,
                moduleName,
                assignment.getSemester(),
                assignment.getYear()
            };
            tableModel.addRow(row);
        }
        
     
        if (tableModel.getRowCount() == 0) {
            tableModel.addRow(new Object[]{
                "No Data",
                "No assignments found for lecturers",
                "-",
                "-",
                "-",
                "-"
            });
        }
    }
    
  
    private User findUserByID(String userID) {
       
        List<User> allLecturers = AssignmentManager.getAllLecturers();
        for (User lecturer : allLecturers) {
            if (lecturer.getUserID().equals(userID) && lecturer.getUserID().startsWith("T")) {
                return lecturer;
            }
        }
        return null;
    }
    

    private void exportReport() {
        StringBuilder report = new StringBuilder();
        report.append("╔════════════════════════════════════════════════════════╗\n");
        report.append("║         LECTURER ASSIGNMENT REPORT                    ║\n");
        report.append("╚════════════════════════════════════════════════════════╝\n\n");
        
        String selectedItem = (String) lecturerCombo.getSelectedItem();
        report.append("Filter: ").append(selectedItem).append("\n");
        report.append("Total Records: ").append(tableModel.getRowCount()).append("\n\n");
        report.append("─────────────────────────────────────────────────────────\n\n");
        
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            report.append("Lecturer ID:   ").append(tableModel.getValueAt(i, 0)).append("\n");
            report.append("Name:          ").append(tableModel.getValueAt(i, 1)).append("\n");
            report.append("Module Code:   ").append(tableModel.getValueAt(i, 2)).append("\n");
            report.append("Module Name:   ").append(tableModel.getValueAt(i, 3)).append("\n");
            report.append("Semester:      ").append(tableModel.getValueAt(i, 4)).append("\n");
            report.append("Year:          ").append(tableModel.getValueAt(i, 5)).append("\n");
            report.append("─────────────────────────────────────────────────────────\n\n");
        }
        
      
        JTextArea textArea = new JTextArea(report.toString());
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        textArea.setEditable(false);
        textArea.setCaretPosition(0);
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(600, 500));
        
        JOptionPane.showMessageDialog(
            this,
            scrollPane,
            "Exported Report",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
}