/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.student.panels;
import utils.FileManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdu
 */
public class StudentCommentPanel extends javax.swing.JPanel {
    private final String COMMENT_PLACEHOLDER = "Type your comment here...";
    private boolean isPlaceholderActive = true;
    private void setupPlaceholder() {
    txtComment.setText(COMMENT_PLACEHOLDER);
    txtComment.setForeground(java.awt.Color.GRAY);
    isPlaceholderActive = true;

    txtComment.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (isPlaceholderActive) {
                txtComment.setText("");
                txtComment.setForeground(java.awt.Color.BLACK);
                isPlaceholderActive = false;
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (txtComment.getText().trim().isEmpty()) {
                txtComment.setText(COMMENT_PLACEHOLDER);
                txtComment.setForeground(java.awt.Color.GRAY);
                isPlaceholderActive = true;
            }
        }
    });
}


    
private static final String COMMENTS_FILE = "data/comments.txt";
private static final String ENROLL_FILE   = "data/enrollments.txt";
private static final String CLASSES_FILE  = "data/classes.txt";

private String currentStudentId;


public void refreshComments(String studentId) {
    this.currentStudentId = studentId;

   
    txtComment.setText(COMMENT_PLACEHOLDER);
    txtComment.setForeground(java.awt.Color.GRAY);
    isPlaceholderActive = true;

    javax.swing.SwingUtilities.invokeLater(() -> {
        txtComment.setCaretPosition(0);
        jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
    });

    loadEnrolledClasses();
}



private List<String> readLinesSafe(String filePath) {
        return FileManager.readFile(filePath);
    }

private void appendLineSafe(String filePath, String line) throws Exception {
        if (!FileManager.appendToFile(filePath, line)) {
            throw new Exception("Failed to append to file: " + filePath);
        }
    }

private void loadEnrolledClasses() {
    cboClass.removeAllItems();

    List<String> classLines = readLinesSafe(CLASSES_FILE);

    for (String c : classLines) {
        String[] cp = c.split("\\|");


        if (cp.length >= 3) {
            String classId = cp[0];
            String className = cp[2];

            String display = classId + " - " + className;
            cboClass.addItem(display);
        }
    }

    if (cboClass.getItemCount() > 0) {
        cboClass.setSelectedIndex(0);
        updateLecturerLabelFromSelectedClass();
    } else {
        lblLecturer.setText("-");
        JOptionPane.showMessageDialog(this, "No classes found.");
    }
}

private void updateLecturerLabelFromSelectedClass() {
    if (cboClass.getSelectedItem() == null) {
        lblLecturer.setText("-");
        return;
    }

    String classId = cboClass.getSelectedItem().toString().split(" - ")[0];
    List<String> classLines = readLinesSafe(CLASSES_FILE);

    for (String c : classLines) {
        String[] cp = c.split("\\|");
        if (cp.length >= 4 && cp[0].equals(classId)) {
            lblLecturer.setText(cp[5]); // lecturerId
            return;
        }
    }
    lblLecturer.setText("-");
}






    public StudentCommentPanel() {
        initComponents();
        setupPlaceholder();
        


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        cboClass = new javax.swing.JComboBox<>();
        lblLecturer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        cboClass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClassActionPerformed(evt);
            }
        });

        lblLecturer.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lblLecturer.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("Lecturer ID:");

        btnSubmit.setBackground(new java.awt.Color(0, 153, 51));
        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Send Comment");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel2.setText("Choose class:");

        txtComment.setColumns(20);
        txtComment.setLineWrap(true);
        txtComment.setRows(5);
        txtComment.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtComment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLecturer))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnSubmit)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboClass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLecturer)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClassActionPerformed
    updateLecturerLabelFromSelectedClass();
    }//GEN-LAST:event_cboClassActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    if (currentStudentId == null || currentStudentId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Student session not found.");
        return;
    }

    if (cboClass.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please select a class.");
        return;
    }

    String comment = txtComment.getText().trim();

    if (comment.isEmpty() || isPlaceholderActive) {
        JOptionPane.showMessageDialog(this, "Please enter a comment.");
        return;
    }

    if (comment.length() > 200) {
        JOptionPane.showMessageDialog(this, "Comment too long (max 200 characters).");
        return;
    }
 

    String classId = cboClass.getSelectedItem().toString().split(" - ")[0];
    String lecturerId = lblLecturer.getText().trim();

    try {

        appendLineSafe(COMMENTS_FILE,
                currentStudentId + "|" + lecturerId + "|" + classId + "|" + comment.replace("\n", " "));

        JOptionPane.showMessageDialog(this, "Comment submitted!");
        txtComment.setText("");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Failed to submit: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboClass;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLecturer;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
