/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.student.panels;
import interfaces.Editable;
import interfaces.Editor;
import utils.FileManager;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Abdu
 */
public class StudentEditProfilePanel extends javax.swing.JPanel implements Editable, Editor {
    
    
    
    private final String EX_FIRST_NAME = "e.g. Ali";
    private final String EX_LAST_NAME  = "e.g. Ahmad";
    private final String EX_PHONE      = "e.g. 0123456789";
    private final String EX_EMAIL      = "e.g. ali@email.com";
    private final String EX_PASSWORD   = "Enter new password";
    
    private void setupExample(javax.swing.JTextField field, String example) {
    field.setText(example);
    field.setForeground(java.awt.Color.GRAY);

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(example)) {
                field.setText("");
                field.setForeground(java.awt.Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().trim().isEmpty()) {
                field.setText(example);
                field.setForeground(java.awt.Color.GRAY);
            }
        }
    });
}







    private static final String USERS_FILE = "data/users.txt";
    private String currentStudentId;

    @Override
    public void loadData() {
        if (currentStudentId == null || currentStudentId.trim().isEmpty()) {
            return;
        }
        loadProfileFromFile();
    }


    @Override
    public void saveChanges() {
        btnSaveActionPerformed(null);
    }

    
    @Override
    public void editProfile() {
        loadData();
    }

    public void refreshProfile(String studentId) {
        
        this.currentStudentId = studentId;

        setupExample(txtFirstName, EX_FIRST_NAME);
        setupExample(txtLastName, EX_LAST_NAME);
        setupExample(txtPhone, EX_PHONE);
        setupExample(txtEmail, EX_EMAIL);

        txtPassword.setText("");
        txtConfirmPassword.setText("");
        

    }

    private List<String> readLinesSafe(String filePath) {
        return FileManager.readFile(filePath);
    }

    private void writeLinesSafe(String filePath, List<String> lines) throws Exception {
        if (!FileManager.writeFile(filePath, lines)) {
            throw new Exception("Failed to write file: " + filePath);
        }
    }



    public StudentEditProfilePanel() {
    initComponents();

    setupExample(txtFirstName, EX_FIRST_NAME);
    setupExample(txtLastName, EX_LAST_NAME);
    setupExample(txtPhone, EX_PHONE);
    setupExample(txtEmail, EX_EMAIL);
}

    
    
    private void loadProfileFromFile() {
        List<String> lines = readLinesSafe(USERS_FILE);

        for (String line : lines) {
            String[] p = line.split("\\|");

                if (p.length >= 9 && p[0].trim().equalsIgnoreCase(currentStudentId.trim())) {

                String fullName = p[3];
                String firstName = "";
                String lastName = "";

                if (fullName.contains(" ")) {
                    int idx = fullName.lastIndexOf(" ");
                    firstName = fullName.substring(0, idx);
                    lastName = fullName.substring(idx + 1);
                    
                } else {
                    firstName = fullName;
                }

                txtFirstName.setText(firstName);
                txtLastName.setText(lastName);

                txtEmail.setText(p[5]);
                txtPhone.setText(p[6]);

                txtPassword.setText("");
                txtConfirmPassword.setText("");

                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Student record not found.");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Last Name");

        btnSave.setBackground(new java.awt.Color(0, 153, 51));
        btnSave.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Update Profile");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("Phone ");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtLastName)))
                            .addComponent(jLabel4)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btnSave)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String firstName = txtFirstName.getText().equals(EX_FIRST_NAME) ? "" : txtFirstName.getText().trim();
        String lastName  = txtLastName.getText().equals(EX_LAST_NAME)  ? "" : txtLastName.getText().trim();
        String phone     = txtPhone.getText().equals(EX_PHONE)         ? "" : txtPhone.getText().trim();
        String email     = txtEmail.getText().equals(EX_EMAIL)         ? "" : txtEmail.getText().trim();


        String password = new String(txtPassword.getPassword()).trim();
        String confirmPassword = new String(txtConfirmPassword.getPassword()).trim();

        if (firstName.isEmpty() || lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name and last name cannot be empty.");
            return;
        }

        if (phone.isEmpty() || !phone.matches("\\d{8,15}")) {
            JOptionPane.showMessageDialog(this, "Phone number must contain only digits (8–15 digits).");
            return;
        }

        if (email.isEmpty() || !email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Invalid email format.");
            return;
        }


        String fullName = firstName + " " + lastName;


        boolean wantsPasswordChange = !password.isEmpty() || !confirmPassword.isEmpty();
        if (wantsPasswordChange) {
            if (password.length() < 6) {
                JOptionPane.showMessageDialog(this, "Password must be at least 6 characters.");
                return;
            }
            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match.");
                return;
            }
        }


        List<String> lines = readLinesSafe(USERS_FILE);
        boolean updated = false;

        for (int i = 0; i < lines.size(); i++) {
            String[] p = lines.get(i).split("\\|");

                if (p.length >= 9 && p[0].trim().equalsIgnoreCase(currentStudentId.trim())) {
                String username = p[1];
                String oldPassword = p[2];
                String gender = p[4];
                String age = p[7];
                String role = p[8];

                String finalPassword = wantsPasswordChange ? password : oldPassword;

                String newLine = currentStudentId + "|" + username + "|" + finalPassword + "|"
                        + fullName + "|" + gender + "|" + email + "|" + phone + "|" + age + "|" + role;

                lines.set(i, newLine);
                updated = true;
                break;
            }
        }

        if (!updated) {
            JOptionPane.showMessageDialog(this, "Student record not found to update.");
            return;
        }

        try {
            writeLinesSafe(USERS_FILE, lines);
            JOptionPane.showMessageDialog(this, "Profile updated successfully!");


            txtPassword.setText("");
            txtConfirmPassword.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to update profile: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
